"""added address3 to shipto

Revision ID: 66d257a5a317
Revises: 968b38d7680e
Create Date: 2023-11-20 17:08:08.330270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66d257a5a317'
down_revision = '968b38d7680e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=True)

    with op.batch_alter_table('ship_to', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address3', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ship_to', schema=None) as batch_op:
        batch_op.drop_column('address3')

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=True)

    # ### end Alembic commands ###
