"""fixed vendor modal, changed vendor to vendor_id

Revision ID: 6df6192f84e9
Revises: 8d4c203a7b77
Create Date: 2023-11-26 10:20:32.218179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6df6192f84e9'
down_revision = '8d4c203a7b77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=True)

    with op.batch_alter_table('purchase__order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('purchase__order_vendor_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'vendor', ['vendor_id'], ['id'])
        batch_op.drop_column('vendor')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase__order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('purchase__order_vendor_fkey', 'vendor', ['vendor'], ['id'])
        batch_op.drop_column('vendor_id')

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=True)

    # ### end Alembic commands ###
