"""Initial migration.

Revision ID: 968b38d7680e
Revises: 
Create Date: 2023-11-20 17:07:44.859005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '968b38d7680e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=True)

    # ### end Alembic commands ###
