"""removed address3 to shipto

Revision ID: 9d4121670e01
Revises: 66d257a5a317
Create Date: 2023-11-20 17:08:28.213403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d4121670e01'
down_revision = '66d257a5a317'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=True)

    with op.batch_alter_table('ship_to', schema=None) as batch_op:
        batch_op.drop_column('address3')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ship_to', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address3', sa.VARCHAR(length=200), autoincrement=False, nullable=True))

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=True)

    # ### end Alembic commands ###
