"""big changes to invoice modal

Revision ID: df81931f9279
Revises: 9d4121670e01
Create Date: 2023-11-20 17:17:41.983105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df81931f9279'
down_revision = '9d4121670e01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('all_items', sa.String(length=500), nullable=True))
        batch_op.drop_constraint('invoice_company_id_fkey', type_='foreignkey')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('invoice_company_id_fkey', 'company', ['company_id'], ['id'])
        batch_op.drop_column('all_items')

    # ### end Alembic commands ###
