"""added vendor cost to items db

Revision ID: 2e93003e1296
Revises: 
Create Date: 2024-01-21 15:41:34.483562

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2e93003e1296'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('final_quote')
    op.drop_table('first_quote')
   
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor_cost', sa.Float(precision=5), nullable=True))
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase__order', schema=None) as batch_op:
        batch_op.alter_column('invoice_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('item_history', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.drop_column('vendor_cost')

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('daily__account', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    op.create_table('first_quote',
    sa.Column('id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('bill_to_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ship_from_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ship_to_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('all_items', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('terms', sa.VARCHAR(length=1200), autoincrement=False, nullable=True),
    sa.Column('invoice_status', sa.VARCHAR(length=1200), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=1200), autoincrement=False, nullable=True),
    sa.Column('extra_info', sa.VARCHAR(length=1200), autoincrement=False, nullable=True),
    sa.Column('bl_number', sa.VARCHAR(length=1200), autoincrement=False, nullable=True),
    sa.Column('bank_details', sa.VARCHAR(length=1200), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=1200), autoincrement=False, nullable=True),
    sa.Column('deleted', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='first_quote_pkey')
    )
    op.create_table('final_quote',
    sa.Column('id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('bill_to_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ship_from_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ship_to_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('all_items', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('terms', sa.VARCHAR(length=1200), autoincrement=False, nullable=True),
    sa.Column('invoice_status', sa.VARCHAR(length=1200), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=1200), autoincrement=False, nullable=True),
    sa.Column('extra_info', sa.VARCHAR(length=1200), autoincrement=False, nullable=True),
    sa.Column('bl_number', sa.VARCHAR(length=1200), autoincrement=False, nullable=True),
    sa.Column('bank_details', sa.VARCHAR(length=1200), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=1200), autoincrement=False, nullable=True),
    sa.Column('deleted', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='final_quote_pkey')
    )
    # ### end Alembic commands ###
