"""Description of changes

Revision ID: 4fc1713af854
Revises: 
Create Date: 2024-01-18 18:26:05.211409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fc1713af854'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill_to', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.String(length=10), nullable=True))

    with op.batch_alter_table('daily__account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=1200), nullable=True))
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('vendor_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bill_to_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('currency', sa.String(length=1200), nullable=True))
     
        batch_op.drop_constraint('daily__account_purchase_order_id_fkey', type_='foreignkey')
        batch_op.drop_column('purchase_order_id')

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_status', sa.String(length=1200), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=1200), nullable=True))
        batch_op.add_column(sa.Column('deleted', sa.String(length=10), nullable=True))
       
        batch_op.alter_column('all_items',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.String(length=1200),
               existing_nullable=True)
        batch_op.alter_column('terms',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.String(length=1200),
               existing_nullable=True)
        batch_op.alter_column('extra_info',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.String(length=1200),
               existing_nullable=True)
        batch_op.alter_column('bl_number',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.String(length=1200),
               existing_nullable=True)
        batch_op.alter_column('bank_details',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.String(length=1200),
               existing_nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.String(length=1200),
               existing_nullable=True)
        batch_op.drop_constraint('invoice_ship_to_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('invoice_ship_from_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('invoice_bill_to_id_fkey', type_='foreignkey')
        batch_op.drop_column('Deli')
        batch_op.drop_column('Manifest')
        batch_op.drop_column('container')
        batch_op.drop_column('status')
        batch_op.drop_column('departure')
        batch_op.drop_column('custom_tracking')
        batch_op.drop_column('location_status')

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('deleted', sa.String(length=10), nullable=True))
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=True)


    with op.batch_alter_table('purchase__order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=1200), nullable=True))
        batch_op.add_column(sa.Column('due_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('purchase_order_status', sa.String(length=1200), nullable=True))
        batch_op.add_column(sa.Column('deleted', sa.String(length=10), nullable=True))
        batch_op.drop_constraint('purchase__order_vendor_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('purchase__order_invoice_id_fkey', type_='foreignkey')
        batch_op.drop_column('bank_details')
        batch_op.drop_column('extra_info')
        batch_op.drop_column('terms')
        batch_op.drop_column('type')
        batch_op.drop_column('Deli')
        batch_op.drop_column('bl_number')
        batch_op.drop_column('Manifest')
        batch_op.drop_column('container')
        batch_op.drop_column('departure')
        batch_op.drop_column('custom_tracking')
        batch_op.drop_column('BL')
        batch_op.drop_column('location_status')

    with op.batch_alter_table('ship_from', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.String(length=10), nullable=True))

    with op.batch_alter_table('ship_to', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.String(length=10), nullable=True))

    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    with op.batch_alter_table('ship_to', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    with op.batch_alter_table('ship_from', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    with op.batch_alter_table('purchase__order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_status', sa.VARCHAR(length=1200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('BL', sa.VARCHAR(length=1200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('custom_tracking', sa.VARCHAR(length=1200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('departure', sa.VARCHAR(length=1200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('container', sa.VARCHAR(length=1200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Manifest', sa.VARCHAR(length=1200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('bl_number', sa.VARCHAR(length=1200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Deli', sa.VARCHAR(length=1200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=1200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('terms', sa.VARCHAR(length=1200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('extra_info', sa.VARCHAR(length=1200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('bank_details', sa.VARCHAR(length=1200), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('purchase__order_invoice_id_fkey', 'invoice', ['invoice_id'], ['id'])
        batch_op.create_foreign_key('purchase__order_vendor_id_fkey', 'vendor', ['vendor_id'], ['id'])
        batch_op.alter_column('invoice_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('deleted')
        batch_op.drop_column('purchase_order_status')
        batch_op.drop_column('due_date')
        batch_op.drop_column('description')

    with op.batch_alter_table('item_history', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.drop_column('deleted')
        batch_op.drop_column('vendor_id')

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_status', sa.VARCHAR(length=10000), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('custom_tracking', sa.VARCHAR(length=10000), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('departure', sa.VARCHAR(length=10000), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=10000), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('container', sa.VARCHAR(length=10000), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Manifest', sa.VARCHAR(length=10000), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Deli', sa.VARCHAR(length=10000), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('invoice_bill_to_id_fkey', 'bill_to', ['bill_to_id'], ['id'])
        batch_op.create_foreign_key('invoice_ship_from_id_fkey', 'ship_from', ['ship_from_id'], ['id'])
        batch_op.create_foreign_key('invoice_ship_to_id_fkey', 'ship_to', ['ship_to_id'], ['id'])
        batch_op.alter_column('type',
               existing_type=sa.String(length=1200),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=True)
        batch_op.alter_column('bank_details',
               existing_type=sa.String(length=1200),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=True)
        batch_op.alter_column('bl_number',
               existing_type=sa.String(length=1200),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=True)
        batch_op.alter_column('extra_info',
               existing_type=sa.String(length=1200),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=True)
        batch_op.alter_column('terms',
               existing_type=sa.String(length=1200),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=True)
        batch_op.alter_column('all_items',
               existing_type=sa.String(length=1200),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('deleted')
        batch_op.drop_column('description')
        batch_op.drop_column('invoice_status')

    with op.batch_alter_table('daily__account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_order_id', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('daily__account_purchase_order_id_fkey', 'purchase__order', ['purchase_order_id'], ['id'])
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('currency')
        batch_op.drop_column('bill_to_id')
        batch_op.drop_column('vendor_id')
        batch_op.drop_column('date')
        batch_op.drop_column('description')

    with op.batch_alter_table('bill_to', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    # ### end Alembic commands ###
