"""added invoice in shipment

Revision ID: 905ae591792f
Revises: 147b72b76786
Create Date: 2024-01-21 17:20:57.993027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '905ae591792f'
down_revision = '147b72b76786'
branch_labels = None
depends_on = None


def upgrade():
   

    with op.batch_alter_table('shipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('invoice_id')

    with op.batch_alter_table('purchase__order', schema=None) as batch_op:
        batch_op.alter_column('invoice_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('item_history', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('vendor_cost',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('daily__account', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###
